spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Shiril - Associate"
    email: "shiril@eazybank.com"
  onCallSupport:
    - (666) 232-8865
    - (666) 778-5671